# kanidm-unixd SSH integration
#
# This config fragment should be placed for example at: /etc/ssh/sshd_config.d/10-kanidm.conf
# Please be aware that OpenSSH supports only a single AuthorizedKeysCommand directive and the first
# one configured takes precedence. If this config fragment is named `10-kanidm.conf` it will
# block for example `20-systemd-userdb.conf` from doing the same.
# Similarly an AuthorizedKeysCommand in /etc/ssh/sshd_config will block this fragment from working!


# Uncomment the lines below to enable SSH access via kanidm-unixd for users configured for PAM login:

#PubkeyAuthentication yes
#UsePAM yes
#AuthorizedKeysCommand /usr/sbin/kanidm_ssh_authorizedkeys %u
#AuthorizedKeysCommandUser nobody
