# coding: utf-8

"""
    Kanidm

    API for interacting with the Kanidm system. This is a work in progress.

    The version of the OpenAPI document: 1.9.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from kanidm_openapi_client.models.auth_step_one_of import AuthStepOneOf
from kanidm_openapi_client.models.auth_step_one_of1 import AuthStepOneOf1
from kanidm_openapi_client.models.auth_step_one_of2 import AuthStepOneOf2
from kanidm_openapi_client.models.auth_step_one_of3 import AuthStepOneOf3
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

AUTHSTEP_ONE_OF_SCHEMAS = ["AuthStepOneOf", "AuthStepOneOf1", "AuthStepOneOf2", "AuthStepOneOf3"]

class AuthStep(BaseModel):
    """
    Authentication to Kanidm is a stepped process.  The session is first initialised with the requested username.  In response the list of supported authentication mechanisms is provided.  The user chooses the authentication mechanism to proceed with.  The server responds with a challenge that the user provides a credential to satisfy. This challenge and response process continues until a credential fails to validate, an error occurs, or successful authentication is complete.
    """
    # data type: AuthStepOneOf
    oneof_schema_1_validator: Optional[AuthStepOneOf] = None
    # data type: AuthStepOneOf1
    oneof_schema_2_validator: Optional[AuthStepOneOf1] = None
    # data type: AuthStepOneOf2
    oneof_schema_3_validator: Optional[AuthStepOneOf2] = None
    # data type: AuthStepOneOf3
    oneof_schema_4_validator: Optional[AuthStepOneOf3] = None
    actual_instance: Optional[Union[AuthStepOneOf, AuthStepOneOf1, AuthStepOneOf2, AuthStepOneOf3]] = None
    one_of_schemas: Set[str] = { "AuthStepOneOf", "AuthStepOneOf1", "AuthStepOneOf2", "AuthStepOneOf3" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AuthStep.model_construct()
        error_messages = []
        match = 0
        # validate data type: AuthStepOneOf
        if not isinstance(v, AuthStepOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStepOneOf`")
        else:
            match += 1
        # validate data type: AuthStepOneOf1
        if not isinstance(v, AuthStepOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStepOneOf1`")
        else:
            match += 1
        # validate data type: AuthStepOneOf2
        if not isinstance(v, AuthStepOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStepOneOf2`")
        else:
            match += 1
        # validate data type: AuthStepOneOf3
        if not isinstance(v, AuthStepOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStepOneOf3`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AuthStep with oneOf schemas: AuthStepOneOf, AuthStepOneOf1, AuthStepOneOf2, AuthStepOneOf3. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AuthStep with oneOf schemas: AuthStepOneOf, AuthStepOneOf1, AuthStepOneOf2, AuthStepOneOf3. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AuthStepOneOf
        try:
            instance.actual_instance = AuthStepOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AuthStepOneOf1
        try:
            instance.actual_instance = AuthStepOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AuthStepOneOf2
        try:
            instance.actual_instance = AuthStepOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AuthStepOneOf3
        try:
            instance.actual_instance = AuthStepOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AuthStep with oneOf schemas: AuthStepOneOf, AuthStepOneOf1, AuthStepOneOf2, AuthStepOneOf3. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AuthStep with oneOf schemas: AuthStepOneOf, AuthStepOneOf1, AuthStepOneOf2, AuthStepOneOf3. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AuthStepOneOf, AuthStepOneOf1, AuthStepOneOf2, AuthStepOneOf3]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


