# coding: utf-8

"""
    Kanidm

    API for interacting with the Kanidm system. This is a work in progress.

    The version of the OpenAPI document: 1.9.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from kanidm_openapi_client.models.cu_reg_state_one_of import CURegStateOneOf
from kanidm_openapi_client.models.cu_reg_state_one_of1 import CURegStateOneOf1
from kanidm_openapi_client.models.cu_reg_state_one_of2 import CURegStateOneOf2
from kanidm_openapi_client.models.cu_reg_state_one_of3 import CURegStateOneOf3
from kanidm_openapi_client.models.cu_reg_state_one_of4 import CURegStateOneOf4
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CUREGSTATE_ONE_OF_SCHEMAS = ["CURegStateOneOf", "CURegStateOneOf1", "CURegStateOneOf2", "CURegStateOneOf3", "CURegStateOneOf4", "str"]

class CURegState(BaseModel):
    """
    CURegState
    """
    # data type: str
    oneof_schema_1_validator: Optional[StrictStr] = None
    # data type: CURegStateOneOf
    oneof_schema_2_validator: Optional[CURegStateOneOf] = None
    # data type: str
    oneof_schema_3_validator: Optional[StrictStr] = None
    # data type: CURegStateOneOf1
    oneof_schema_4_validator: Optional[CURegStateOneOf1] = None
    # data type: str
    oneof_schema_5_validator: Optional[StrictStr] = None
    # data type: CURegStateOneOf2
    oneof_schema_6_validator: Optional[CURegStateOneOf2] = None
    # data type: CURegStateOneOf3
    oneof_schema_7_validator: Optional[CURegStateOneOf3] = None
    # data type: CURegStateOneOf4
    oneof_schema_8_validator: Optional[CURegStateOneOf4] = None
    actual_instance: Optional[Union[CURegStateOneOf, CURegStateOneOf1, CURegStateOneOf2, CURegStateOneOf3, CURegStateOneOf4, str]] = None
    one_of_schemas: Set[str] = { "CURegStateOneOf", "CURegStateOneOf1", "CURegStateOneOf2", "CURegStateOneOf3", "CURegStateOneOf4", "str" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CURegState.model_construct()
        error_messages = []
        match = 0
        # validate data type: str
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: CURegStateOneOf
        if not isinstance(v, CURegStateOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CURegStateOneOf`")
        else:
            match += 1
        # validate data type: str
        try:
            instance.oneof_schema_3_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: CURegStateOneOf1
        if not isinstance(v, CURegStateOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CURegStateOneOf1`")
        else:
            match += 1
        # validate data type: str
        try:
            instance.oneof_schema_5_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: CURegStateOneOf2
        if not isinstance(v, CURegStateOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CURegStateOneOf2`")
        else:
            match += 1
        # validate data type: CURegStateOneOf3
        if not isinstance(v, CURegStateOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CURegStateOneOf3`")
        else:
            match += 1
        # validate data type: CURegStateOneOf4
        if not isinstance(v, CURegStateOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CURegStateOneOf4`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CURegState with oneOf schemas: CURegStateOneOf, CURegStateOneOf1, CURegStateOneOf2, CURegStateOneOf3, CURegStateOneOf4, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CURegState with oneOf schemas: CURegStateOneOf, CURegStateOneOf1, CURegStateOneOf2, CURegStateOneOf3, CURegStateOneOf4, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CURegStateOneOf
        try:
            instance.actual_instance = CURegStateOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_3_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CURegStateOneOf1
        try:
            instance.actual_instance = CURegStateOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_5_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_5_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CURegStateOneOf2
        try:
            instance.actual_instance = CURegStateOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CURegStateOneOf3
        try:
            instance.actual_instance = CURegStateOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CURegStateOneOf4
        try:
            instance.actual_instance = CURegStateOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CURegState with oneOf schemas: CURegStateOneOf, CURegStateOneOf1, CURegStateOneOf2, CURegStateOneOf3, CURegStateOneOf4, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CURegState with oneOf schemas: CURegStateOneOf, CURegStateOneOf1, CURegStateOneOf2, CURegStateOneOf3, CURegStateOneOf4, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CURegStateOneOf, CURegStateOneOf1, CURegStateOneOf2, CURegStateOneOf3, CURegStateOneOf4, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


