# coding: utf-8

"""
    Kanidm

    API for interacting with the Kanidm system. This is a work in progress.

    The version of the OpenAPI document: 1.9.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from kanidm_openapi_client.models.unix_group_token import UnixGroupToken
from typing import Optional, Set
from typing_extensions import Self

class UnixUserToken(BaseModel):
    """
    A token representing the details of a unix user
    """ # noqa: E501
    name: StrictStr
    spn: StrictStr
    displayname: StrictStr
    gidnumber: Annotated[int, Field(strict=True, ge=0)]
    uuid: UUID
    shell: Optional[StrictStr] = None
    groups: List[UnixGroupToken]
    sshkeys: List[StrictStr]
    valid: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "spn", "displayname", "gidnumber", "uuid", "shell", "groups", "sshkeys", "valid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnixUserToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # set to None if shell (nullable) is None
        # and model_fields_set contains the field
        if self.shell is None and "shell" in self.model_fields_set:
            _dict['shell'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnixUserToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "spn": obj.get("spn"),
            "displayname": obj.get("displayname"),
            "gidnumber": obj.get("gidnumber"),
            "uuid": obj.get("uuid"),
            "shell": obj.get("shell"),
            "groups": [UnixGroupToken.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "sshkeys": obj.get("sshkeys"),
            "valid": obj.get("valid")
        })
        return _obj


