---
name: "Build Deb Packages"

# The high level logic is to:
# 1. crossbuild the target triplet via cross (auto native for x86_64)
# 2. build debs for the target triplet via cargo-deb
# 3. Push the debs to a specific release. This step is a dirty hack that should go away.

"on":
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-deb-package:
    name: Build deb packages
    strategy:
      matrix:
        image:
          - name: ubuntu
            version: 22.04
          - name: debian
            version: 12
        target:
          - name: x86_64-unknown-linux-gnu
            debian-name: amd64
            features: native-deps  # crossbuilds take care of deps in their Dockerfile, native ignores Docker
          - name: aarch64-unknown-linux-gnu
            debian-name: arm64
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Dump matrix spec
        run: "echo Matrix: ${{ matrix.image.name }}-${{ matrix.image.version }}-${{ matrix.target.name }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Maybe install native build deps
        # actions-rust-cross is a bit too "clever" and bypasses cross building when native, which then ignores our deps
        if: matrix.target.features == 'native-deps'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libssl3 libssl-dev \
            libudev-dev \
            libpam0g-dev
      # Step 1. crossbuild
      - name: Build packages (cross bins)
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target.name }}
          args: "--locked --release --bin kanidm_ssh_authorizedkeys --bin kanidm_unixd --bin kanidm_unixd_tasks --bin kanidm-unix"
        env:
          CROSS_CONFIG: "platform/crossbuild/${{ matrix.image.name }}-${{ matrix.image.version }}-${{ matrix.target.name }}/Cross.toml"
      - name: Build packages (cross sdylibs)
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target.name }}
          args: "--locked --release -p pam_kanidm -p nss_kanidm"
        env:
          CROSS_CONFIG: "platform/crossbuild/${{ matrix.image.name }}-${{ matrix.image.version }}-${{ matrix.target.name }}/Cross.toml"
      - name: Install deb build dependencies
        run: |
            # Since we use ubuntu-latest as the workflow image, the build OS is always ubuntu regardless of the matrix
            platform/debian/install_ci_build_dependencies.sh \
              "ubuntu" \
              "${{ matrix.target.debian-name }}"
            cargo install cargo-deb
      # Step 2. deb build
      - name: Build packages (debs)
        run: |
          platform/debian/build_debs.sh "${{ matrix.target.name }}"
        env:
          SKIP_DEPS: 1  # Already done in separate step

      - name: Upload debs
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.image.name }}${{ matrix.image.version }}"
          path: |
            target/${{ matrix.target.name }}/debian/*.deb

  # Step 3. Create deb release
  upload-to-releases:
    permissions:
      # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write  # allows the action to create a release

    name: Upload to releases
    needs: build-deb-package
    runs-on: ubuntu-latest
    steps:
      - name: Download previously built debs
        uses: actions/download-artifact@v4
        with:
          path: debs
          merge-multiple: true
      - name: List packages
        run: |
          find $(pwd) -name '*.deb'
      # TODO: This action is old and falling apart and will soon stop working.
      # Context: https://github.com/marvinpinto/action-automatic-releases/pull/2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "debs"
          prerelease: true
          title: ".deb Packages"
          files: "debs/*.deb"
        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'kanidm/kanidm' }}
