---
name: "Linux Build and Test"
# Trigger the workflow on push to master or pull request
"on":
  push:
    branches:
      - master
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust_build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        rust_version: ["stable", "nightly"]
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libpam0g-dev \
            libudev-dev \
            libssl-dev \
            libsystemd-dev \
            ripgrep

      - name: "Run cargo test"
        run: cargo test

      - name: "Build the workspace"
        run: cargo build --locked --workspace

      - name: "Run the release build test script"
        run: |
          python -m pip install uv
          ./scripts/test_run_release_server.sh

