#!/bin/sh
# prerm script for kanidm
# rename this to remove the .ex to make it usable.
#
# see: dh_installdeb(1)

set -e


case "$1" in
    remove|upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
